# Generated by Django 5.0.6 on 2026-06-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("PREMIUM", "Telegram Premium"),
                            ("STARS", "Telegram Stars"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("duration_months", models.IntegerField(blank=True, null=True)),
                ("stars_amount", models.IntegerField(blank=True, null=True)),
                ("price_toman", models.DecimalField(decimal_places=0, max_digits=14)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["product_type", "price_toman"],
            },
        ),
    ]
